name: Release docs

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          path: ./docs/magenta-meteorite # The root location of your Astro project inside the repository. (optional)
          # node-version: 20 # The specific version of Node that should be used to build your site. Defaults to 20. (optional)
        # package-manager: pnpm@latest # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

#  pdf:
#    needs: deploy
#    runs-on: ubuntu-latest
#    container:
#      image: node:20-bullseye
#    steps:
#      - name: Wait
#        run: sleep 30
#
#      - name: Install dependencies
#        run: |
#          apt-get update && apt-get install -y chromium chromium-sandbox --no-install-recommends
#          npm install -g starlight-to-pdf
#
#      - name: Generate PDF
#        run: |
#          export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
#          npx starlight-to-pdf https://br7rkr.github.io/ProjectForVk -- --no-sandbox --disable-setuid-sandbox
#
#      - name: Upload PDF artifact
#        uses: actions/upload-artifact@v4
#        with:
#            name: documentation-pdf
#            path: output.pdf
#
#  create-release:
#    needs: pdf
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download artifacts
#        uses: actions/download-artifact@v4
#        with:
#          name: documentation-pdf
#          path: ./
#
#      - name: Create Release
#        id: create_releasef
#        uses: softprops/action-gh-release@v2
#        with:
#          tag_name: ${{ github.ref }}
#          name: "Release ${{ github.ref_name }}"
#          draft: false
#          prerelease: ${{ contains(github.ref, 'alpha') }}
#          files: |
#            output.pdf
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}